---
- hosts: docker-server
  gather_facts: no
  tasks:
    - name: copy war onto docker server
      copy:
        src: /opt/playbooks/webapp/target//webapp.war
        dest: /opt/docker
  tasks:
    - name: delete and create the container
      command: docker stop gaurav_image; docker rm -f gaurav_image; docker image rm -f gaurav_image; cd /opt/docker; docker build -t gaurav_image .
      command: docker run -d --name gaurav_image -p 8090:8080 gaurav_image
      
      
    