---
- hosts: docker-server
  tasks:
    - name: Stop a container
      docker_container:
        name: gaurav_image
        state: stopped   

    - name: remove container
      docker_container:
        name: gaurav_image
        state: absent

    - name: Remove image
      docker_image:
        state: absent
        name: gaurav_image
            
    - name: build the image
      command: docker build -t gaurav_image /opt/docker/

  